services:
  daprclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "60001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  daprclient-dapr:
    command: ["./daprd",
      "-app-id", "daprclient",
      "-app-port", "80",
      "-app-protocol", "grpc",
      "-dapr-grpc-port", "5005",
      "-dapr-http-port", "3500",
      "-components-path", "/dapr"
    ]
    ports: []
    volumes:
      - "./dapr:/dapr"

  daprserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "60002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  daprserver-dapr:
    command: ["./daprd",
      "-app-id", "daprserver",
      "-app-port", "80",
      "-app-protocol", "grpc",
      "-dapr-grpc-port", "5005",
      "-dapr-http-port", "3500",
      "-components-path", "/dapr"
    ]
    ports: []
    volumes:
      - "./dapr:/dapr"
